FROM openshift/origin-release:golang-1.10
COPY . /go/src/github.com/kubernetes-csi/external-attacher/
RUN cd /go/src/github.com/kubernetes-csi/external-attacher/ && \
    go build ./cmd/csi-attacher

FROM centos:7

COPY --from=0 /go/src/github.com/kubernetes-csi/external-attacher/csi-attacher /usr/bin/

RUN useradd csi-attacher
USER csi-attacher

ENTRYPOINT ["/usr/bin/csi-attacher"]
