FROM --platform=$BUILDPLATFORM golang:1.13.3 AS builder
ARG TARGETPLATFORM
ARG BUILDPLATFORM
WORKDIR /code
ADD . /code/

RUN cd /code/ && GOARCH=$(echo $TARGETPLATFORM | cut -f2 -d '/') make build

FROM gcr.io/distroless/static:latest
LABEL maintainers="Kubernetes Authors"
LABEL description="CSI External Attacher"

COPY --from=builder /code/bin/csi-attacher csi-attacher
ENTRYPOINT ["/csi-attacher"]
